# Generated by Django 3.2.13 on 2024-06-23 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_passwordreset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyclient',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='companyclient',
            name='manager_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
