# Generated by Django 5.0.6 on 2024-06-25 02:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20240623_2015'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyclient',
            options={'verbose_name': 'Client Entreprise', 'verbose_name_plural': 'Clients Entreprise'},
        ),
        migrations.AlterModelOptions(
            name='personalclient',
            options={'verbose_name': 'Client Personnel', 'verbose_name_plural': 'Clients Personnels'},
        ),
        migrations.AlterModelOptions(
            name='producer',
            options={'verbose_name': 'Producteur', 'verbose_name_plural': 'Producteurs'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Produit', 'verbose_name_plural': 'Produits'},
        ),
        migrations.AlterModelOptions(
            name='province',
            options={'verbose_name': 'Province', 'verbose_name_plural': 'Provinces'},
        ),
        migrations.AlterModelOptions(
            name='purchase',
            options={'verbose_name': 'Achat', 'verbose_name_plural': 'Achats'},
        ),
        migrations.AlterModelOptions(
            name='sale',
            options={'verbose_name': 'Vente', 'verbose_name_plural': 'Ventes'},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'verbose_name': 'Fournisseur', 'verbose_name_plural': 'Fournisseurs'},
        ),
        migrations.AlterField(
            model_name='personalclient',
            name='province',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personal_client_province', to='inventory.province'),
        ),
    ]
