# Generated by Django 5.0.6 on 2024-06-21 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('inventory', '0003_producer_is_approved_alter_producer_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producer',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='producers', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='producer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='producer',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='producer',
            name='product',
            field=models.ManyToManyField(blank=True, related_name='producers', to='inventory.product'),
        ),
        migrations.AlterField(
            model_name='producer',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='producer_users', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
