# Generated by Django 5.0.6 on 2024-06-21 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_producer_groups_alter_producer_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producer',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
    ]
