# Generated by Django 5.0.6 on 2024-06-22 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_producer_options_alter_producer_managers_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producer',
            old_name='is_active',
            new_name='is_actived',
        ),
    ]
